fix: fix cd

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -26,6 +26,16 @@ jobs:
       - name: Run unit tests
         run: npm run test:cov
         working-directory: .
+
+      - name: Verify coverage report exists
+        run: |
+          if [ -f coverage/unit/lcov.info ]; then
+            echo "Coverage report found."
+          else
+            echo "Coverage report NOT found!" >&2
+            exit 1
+          fi
+        working-directory: .
         
       - name: Run e2e tests
         run: npm run test:e2e
